#!/usr/bin/env python3

import os
import sys
import traceback

sys.dont_write_bytecode = True
sys.excepthook = traceback.print_exception

import core.main as cm

cm.main(sys.argv[1:], os.path.normpath(os.path.abspath(__file__)))
